name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: make
      run: make

    - name: run
      run: timeout 10s ./server; timeout 10s ./client
      
    - name: make bonus
      run: make bonus

    - name: run bonus
      run: timeout 10s ./server_bonus; timeout 10s ./client_bonus
