name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential procps

    - name: Compile project
      run: make

    - name: Test client-server communication
      run: |
        # Start server in background
        ./server &
        
        sleep 2

        # Send test message via client
        ./client $(pgrep -n server) "Hello from GitHub Actions!"

        # Kill server (forcefully if needed)
        kill -9  $(pgrep -n server) || true
      timeout-minutes: 2
