name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile project
      run: make

    - name: Test client-server communication
      run: |
        # Start the server in the background and capture its PID
        ./server > server.log 2>&1 &
        SERVER_PID=$!

        # Wait for the server to start and print its PID
        sleep 2  # Give the server time to initialize
        SERVER_PID=$(grep -oP "PID: \K\d+" server.log)
        echo "Server PID: $SERVER_PID"

        # Send a message via the client
        ./client "$SERVER_PID" "Hello from GitHub Actions!"

        # Terminate the server after the test
        kill "$SERVER_PID" || true
      timeout-minutes: 2 
